/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CardList {
    }
    interface CardListItem {
        "imageUrl": string;
        "title": string;
    }
}
declare global {
    interface HTMLCardListElement extends Components.CardList, HTMLStencilElement {
    }
    var HTMLCardListElement: {
        prototype: HTMLCardListElement;
        new (): HTMLCardListElement;
    };
    interface HTMLCardListItemElement extends Components.CardListItem, HTMLStencilElement {
    }
    var HTMLCardListItemElement: {
        prototype: HTMLCardListItemElement;
        new (): HTMLCardListItemElement;
    };
    interface HTMLElementTagNameMap {
        "card-list": HTMLCardListElement;
        "card-list-item": HTMLCardListItemElement;
    }
}
declare namespace LocalJSX {
    interface CardList {
    }
    interface CardListItem {
        "imageUrl"?: string;
        "title"?: string;
    }
    interface IntrinsicElements {
        "card-list": CardList;
        "card-list-item": CardListItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "card-list": LocalJSX.CardList & JSXBase.HTMLAttributes<HTMLCardListElement>;
            "card-list-item": LocalJSX.CardListItem & JSXBase.HTMLAttributes<HTMLCardListItemElement>;
        }
    }
}
